clair:
  port: 6060
  healthPort: 6061
  uri: http://clair
  priority: Low
  report:
    path: ./reports
    format: html
auth:
  registry: # = service argument in Www-authenticate header of the registry 401 response
    user: jgsqware
    password: jgsqware
  registry_docker_io: # = value of HUB repository
    user: jgsqware
    password: ""
  quay_io:
    user: jgsqware
    password: ""
  insecureSkipVerify: true
hyperclair:
  uri: http://hyperclair
  port: 9999
