clair:
  port: 6060
  healthPort: 6061
  uri: http://clair
  priority: Low
  report:
    path: ./reports
    format: html
auth:
  insecureSkipVerify: true
hyperclair:
  uri: http://hyperclair
  port: 9999
